# Generated by Django 4.2.3 on 2023-07-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_docker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
