# Generated by Django 4.2.3 on 2023-07-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_docker', '0002_rename_dob_employeeprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='outside_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
